# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 21:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarShare', '0002_travelling'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelling',
            name='car_model',
            field=models.CharField(default='default', max_length=128),
        ),
        migrations.AddField(
            model_name='travelling',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2012, 3, 1, 10, 0)),
        ),
        migrations.AddField(
            model_name='travelling',
            name='driver_fullname',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='travelling',
            name='phone',
            field=models.CharField(default='default', max_length=32),
        ),
    ]
