# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 22:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CarShare', '0003_auto_20170119_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelling',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 19, 22, 23, 43, 219958, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='travelling',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 20, 10, 0)),
        ),
    ]
