# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 22:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CarShare', '0004_auto_20170119_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelling',
            name='car_model',
            field=models.CharField(default='model', max_length=128),
        ),
        migrations.AlterField(
            model_name='travelling',
            name='driver_fullname',
            field=models.CharField(default='fullname', max_length=255),
        ),
        migrations.AlterField(
            model_name='travelling',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 19, 22, 49, 48, 449215, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='travelling',
            name='phone',
            field=models.CharField(default='123456789', max_length=32),
        ),
    ]
